import nltk
import string
nltk.download('vader_lexicon')

def news_article_headlines():
    """
    Uses the newsapi API in order to get the top headlines of any given day. 
    This function inputs different headlines into separate values of a list.
    Then, it returns the list which is used in other functions.
    """
    from newsapi import NewsApiClient

    import requests
    url = ('https://newsapi.org/v2/top-headlines?'
        'country=us&'
        'apiKey=12bcd741cfe7426ea4df9c970e781394')
    response = requests.get(url)
    #Code is from NewsAPI website
    #https://newsapi.org/docs/get-started#top-headlines

    a = response.json()
    #print(a)

    headlines = []

    for i in a["articles"]:
        headlines.append(i["title"])

    return headlines

def headlines_sentiment():
    """
    This code uses the news_article_headlines() function and analyzes it to
    assess the market sentiment using sentiment analysis. The nltk package
    is used to evaluate the sentiment of each headline. Then we find the
    average of each headline to get the average sentiment of all headlines.
    We would assume that this value would be accurate in determining the market sentiment.
    """
    from nltk.sentiment.vader import SentimentIntensityAnalyzer

    total_sentiment = 0

    for i in range(len(news_article_headlines())):
        sentence = news_article_headlines()[i]
        #print(sentence)
        score = SentimentIntensityAnalyzer().polarity_scores(sentence)
        #print(score['compound'])
        total_sentiment += score['compound']
    
    average_sentiment = total_sentiment/(len(news_article_headlines()))
    #print(average_sentiment)
    return average_sentiment

    # print(len(news_article_headlines()))
    # print(news_article_headlines()[1])

def sentiment_result(sentiment_n):
    """
    This function outputs a result text based on market sentiment from either nltk or custom analysis.
    If the input value is positive, it will return a positive string.
    If the input value is negative, it will return a negative string.
    If the input value is 0, it will return a "neutral" text.
    """
    a = sentiment_n()
    
    if a > 0:
        return "Based on current news headlines, the current market sentiment is positive!"
    elif a < 0:
        return "Based on current news headlines, the current market sentiment is negative!"
    else:
        return "Based on current news headlines, the current market sentiment is neutral!"

def custom_word_rankings():
    """
    This is a function that stores a very large dictionary. This dictionary was generated
    using ChatGPT in order to rank from -100 to 100 the sentiment of various words.
    I used the following prompts:
        # List positive and negative works and rank their positivity from -100 to 100
        # General words. Ex: "bad" would be negative, so it would be a negative number
        # List a lot more words and format it into a python dictionary

    """

    word_rankings = {'Love': 100,
    'Joy': 95,
    'Happiness': 90,
    'Gratitude': 85,
    'Peace': 80,
    'Success': 75,
    'Kindness': 70,
    'Generosity': 65,
    'Laughter': 60,
    'Hope': 55,
    'Friendship': 50,
    'Beauty': 45,
    'Trust': 40,
    'Wisdom': 35,
    'Creativity': 30,
    'Humor': 25,
    'Health': 20,
    'Freedom': 15,
    'Respect': 10,
    'Comfort': 5,
    'Chair': 0,
    'Table': 0,
    'Car': 0,
    'Phone': 0,
    'House': 0,
    'Computer': 0,
    'Tree': 0,
    'Lamp': 0,
    'Shirt': 0,
    'Book': 0,
    'Hate': -100,
    'Anger': -95,
    'Sadness': -90,
    'Despair': -85,
    'War': -80,
    'Failure': -75,
    'Cruelty': -70,
    'Greed': -65,
    'Fear': -60,
    'Disappointment': -55,
    'Evil': -50,
    'Pain': -45,
    'Betrayal': -40,
    'Ignorance': -35,
    'Boredom': -30,
    'Sickness': -25,
    'Captivity': -20,
    'Oppression': -15,
    'Insult': -10,
    'Inconvenience': -5,
    'Excitement': 25,
    'Curiosity': 30,
    'Satisfaction': 45,
    'Accomplishment': 70,
    'Adventure': 50,
    'Comfortable': 35,
    'Empathy': 40,
    'Serenity': 55,
    'Faith': 60,
    'Trustworthy': 75,
    'Confident': 80,
    'Thrilling': 85,
    'Exhilarating': 90,
    'Fascinating': 95,
    'Uplifting': 100,
    'Smile': 60,
    'Sunshine': 80,
    'Calm': 65,
    'Pleasure': 75,
    'Goodness': 85,
    'Contentment': 70,
    'Blessing': 90,
    'Cheerful': 75,
    'Enthusiasm': 55,
    'Optimism': 50,
    'Bravery': 80,
    'Courage': 75,
    'Gracious': 65,
    'Mercy': 80,
    'Empowerment': 70,
    'Humility': 60,
    'Innovation': 50,
    'Simplicity': 45,
    'Spirituality': 65,
    'Charm': 55,
    'Admiration': 70,
    'Dignity': 75,
    'Efficiency': 50,
    'Adventurous': 75,
    'Radiance': 85,
    'Affection': 85,
    'Fulfillment': 75,
    'Harmony': 70,
    'Insightful': 65,
    'Passion': 80,
    'Perspective': 60,
    'Pride': 55,
    'Rejoice': 70,
    'Resilience': 75,
    'Sincerity': 60,
    'Soulful': 65,
    'Stimulating': 75,
    'Thankfulness': 80,
    'Thorough': 70,
    'Tolerance': 65,
    'Tranquility': 80,
    'Understanding': 75,
    'Valuable': 70,
    'Vitality': 75,
    'Warmth': 80,
    'Wonder': 75,
    'Zeal': 80,
    'Apathetic': -60,
    'Arrogant': -80,
    'Awkward': -70,
    'Barbaric': -90,
    'Bewildered': -55,
    'Boring': -65,
    'Brutal': -85,
    'Clumsy': -75,
    'Cold': -65,
    'Confused': -60,
    'Cowardly': -80,
    'Cruel': -90,
    'Deceitful': -85,
    'Defeat': -75,
    'Defensive': -70,
    'Depression': -85,
    'Desperate': -90,
    'Destructive': -85,
    'Difficult': -65,
    'Disagreeable': -75,
    'Disastrous': -90,
    'Disgusting': -85,
    'Dishonest': -85,
    'Disrespectful': -80,
    'Dissatisfied': -75,
    'Distasteful': -70,
    'Distressing': -80,
    'Dreadful': -90,
    'Egotistical': -80,
    'Embarrassed': -70,
    'Envious': -75,
    'Erratic': -70,
    'Exhausted': -75,
    'Foolish': -80,
    'Frantic': -75,
    'Frustrated': -80,
    'Furious': -90,
    'Gloomy': -70,
    'Greedy': -85,
    'Grief': -85,
    'Grim': -75,
    'Gruesome': -90,
    'Guilty': -75,
    'Hard-hearted': -80,
    'Harmful': -85,
    'Hateful': -90,
    'Heartless': -85,
    'Helpless': -70,
    'Hesitant': -60,
    'Hopeless': -90,
    'Horrendous': -90,
    'Horrible': -90,
    'Hostile': -80,
    'Humiliated': -75,
    'Hurtful': -85,
    'Hysterical': -75,
    'Ignorant': -80,
    'Immobile': -70,
    'Impatient': -65,
    'Impolite': -75,
    'Inadequate': -70,
    'Inattentive': -65,
    'Incapable': -70,
    'Inconsiderate': -75,
    'Indecisive': -70,
    'Indifferent': -60,
    'Indignant': -75,
    'Inferior': -75,
    'Inhibited': -70,
    'Insecure': -75,
    'Insensitive': -80,
    'Insincere': -80,
    'Insulting': -85,
    'Intolerant': -85,
    'Irresponsible': -80,
    'Jealous': -85,
    'Lazy': -75,
    'Lifeless': -70,
    'Lonely': -75,
    'Lousy': -80,
    'Mad': -85,
    'Mean': -85,
    'Melancholy': -70,
    'Miserable': -90,
    'Misunderstood': -75,
    'Moody': -70,
    'Nasty': -85,
    'Naughty': -75,
    'Negative': -75,
    'Nervous': -70,
    'Nonchalant': -60,
    'Numb': -70,
    'Offensive': -85,
    'Outrageous': -90,
    'Overwhelmed': -75,
    'Painful': -85,
    'Panicky': -75,
    'Paranoid': -85,
    'Pathetic': -80,
    'Pessimistic': -85,
    'Petrified': -80,
    'Phony': -85,
    'Pitiful': -80,
    'Powerless': -75,
    'Prejudiced': -85,
    'Procrastinating': -70,
    'Provoking': -80,
    'Puny': -70,
    'Puzzled': -65,
    'Quarrelsome': -75,
    'Questionable': -70,
    'Quiet': -60,
    'Quivering': -70,
    'Rash': -70,
    'Rebellious': -75,
    'Repugnant': -85,
    'Repulsive': -85,
    'Resentful': -80,
    'Restless': -70,
    'Ridiculous': -80,
    'Rotten': -85,
    'Rude': -85,
    'Sad': -75,
    'Savage': -90,
    'Scared': -70,
    'Scheming': -85,
    'Scornful': -80,
    'Secretive': -70,
    'Sedentary': -70,
    'Self-centered': -80,
    'Self-conscious': -70,
    'Self-indulgent': -75,
    'Selfish': -85,
    'Self-pitying': -75,
    'Self-rejecting': -80,
    'Shaky': -70,
    'Shallow': -70,
    'Shameful': -80,
    'Shameless': -80,
    'Shock': -85,
    'Shy': -65,
    'Silly': -70,
    'Sneaky': -80,
    'Sore': -75,
    'Sorry': -75,
    'Spineless': -75,
    'Stressed': -80,
    'Stuck': -70,
    'Stupid': -85,
    'Submissive': -75,
    'Suffering': -85,
    'Suspicious': -80,
    'Tense': -70,
    'Terrible': -90,
    'Terrified': -80,
    'Threatened': -75,
    'Timid': -65,
    'Tired': -75,
    'Tragic': -85,
    'Troubled': -75,
    'Ugly': -80,
    'Unappreciated': -75,
    'Uncertain': -70,
    'Uncomfortable': -75,
    'Unconscious': -70,
    'Unconventional': -60,
    'Undesirable': -75,
    'Unhappy': -80,
    'Unimportant': -70,
    'Unimpressed': -70,
    'Unloved': -80,
    'Unmotivated': -75,
    'Unpleasant': -80,
    'Unpopular': -75,
    'Unreliable': -80,
    'Unresolved': -75,
    'Unsatisfied': -80,
    'Unsure': -70,
    'Unworthy': -80,
    'Upset': -75,
    'Useless': -80,
    'Vacant': -70,
    'Vague': -70,
    'Vain': -75,
    'Venomous': -85,
    'Vengeful': -85,
    'Vexed': -80,
    'Vicious': -90,
    'Victimized': -80,
    'Vile': -85,
    'Villainous': -90,
    'Violated': -80,
    'Violent': -90,
    'Volatile': -75,
    'Vulnerable': -75,
    'Wary': -70,
    'Weak': -75,
    'Weary': -75,
    'Weird': -70,
    'Wicked': -90,
    'Wild': -70,
    'Wimpy': -70,
    'Wishy-washy': -70,
    'Withdrawn': -70,
    'Worried': -75,
    'Worthless': -85,
    'Wounded': -80,
    'Wronged': -80,
    'Yearning': -60,
    'Yellow-bellied': -75,
    'Zealous': 85,
    'Zestful': 85,
    'Able': 80,
    'Abundant': 80,
    'Accepting': 75,
    'Accommodating': 75,
    'Accomplished': 85,
    'Adaptable': 80,
    'Admired': 85,
    'Adorable': 85,
    'Adored': 85,
    'Advanced': 80,
    'Affable': 85,
    'Affectionate': 85,
    'Agile': 80,
    'Agreeable': 85,
    'Alert': 80,
    'Aligned': 75,
    'Alive': 75,
    'Alluring': 80,
    'Altruistic': 85,
    'Amazing': 90,
    'Ambitious': 80,
    'Amiable': 85,
    'Amused': 75,
    'Animated': 80,
    'Appreciated': 85,
    'Appreciative': 85,
    'Articulate': 80,
    'Artistic': 80,
    'Assertive': 80,
    'Astute': 80,
    'Attractive': 85,
    'Authentic': 85,
    'Aware': 75,
    'Awesome': 90,
    'Balanced': 75,
    'Beautiful': 85,
    'Believable': 75,
    'Beloved': 85,
    'Beneficent': 85,
    'Beneficial': 85,
    'Benevolent': 85,
    'Best': 90,
    'Blessed': 85,
    'Blissful': 85,
    'Bold': 80,
    'Brainy': 75,
    'Brave': 80,
    'Bright': 80,
    'Brilliant': 90,
    'Calm': 75,
    'Candid': 75,
    'Capable': 80,
    'Captivating': 85,
    'Carefree': 75,
    'Careful': 75,
    'Caring': 85,
    'Celebrated': 85,
    'Centered': 75,
    'Champion': 85,
    'Charismatic': 85,
    'Charming': 85,
    'Cheerful': 85,
    'Cherished': 85,
    'Chosen': 80,
    'Clever': 80,
    'Close-knit': 80,
    'Collaborative': 80,
    'Comfortable': 80,
    'Comical': 75,
    'Commendable': 80,
    'Committed': 80,
    'Compassionate': 85,
    'Confident': 85,
    'Congruent': 75,
    'Connected': 75,
    'Conscious': 75,
    'Considerate': 85,
    'Consistent': 75,
    'Content': 75,
    'Convenient': 75,
    'Convivial': 80,
    'Cool': 75,
    'Cooperative': 80,
    'Courageous': 85,
    'Courteous': 85,
    'Creative': 80,
    'Credible': 75,
    'Cuddly': 80,
    'Cultivated': 75,
    'Cultured': 75,
    'Curious': 75,
    'Dandy': 80,
    'Daring': 80,
    'Dazzling': 85,
    'Debonair': 80,
    'Decent': 75,
    'Decisive': 80,
    'Dedicated': 85,
    'Deep': 75,
    'Delicious': 80,
    'Delightful': 85,
    'Dependable': 85,
    'Desirable': 80,
    'Detailed': 75,
    'Determined': 85,
    'Devoted': 85,
    'Dignified': 80,
    'Diligent': 85,
    'Diplomatic': 80,
    'Direct': 75,
    'Discerning': 75,
    'Discreet': 75,
    'Distinguished': 85,
    'Divine': 85,
    'Dreamy': 80,
    'Driven': 80,
    'Dynamic': 80,
    'Eager': 75,
    'Earnest': 80,
    'Easygoing': 75,
    'Eclectic': 75,
    'Economical': 75,
    'Ecstatic': 85,
    'Educated': 75,
    'Effective': 80,
    'Effervescent': 80,
    'Efficient': 80,
    'Elegant': 85,
    'Eloquent': 80,
    'Empathetic': 85,
    'Energetic': 80,
    'Engaging': 85,
    'Enlightened': 75,
    'Enterprising': 80,
    'Entertaining': 80,
    'Enthusiastic': 85,
    'Entrepreneurial': 80,
    'Ephemeral': 75,
    'Equal': 75,
    'Equitable': 75,
    'Ethical': 75,
    'Euphoric': 85,
    'Evenhanded': 75,
    'Everlasting': 75,
    'Evolving': 75,
    'Exact': 75,
    'Excellent': 90,
    'Exciting': 85,
    'Exemplary': 85,
    'Exhilarating': 85,
    'Expansive': 75,
    'Experienced': 75,
    'Expert': 80,
    'Expressive': 80,
    'Extraordinary': 90,
    'Exuberant': 85,
    'Fabulous': 85,
    'Fair': 75,
    'Faithful': 85,
    'Famous': 85,
    'Fantastic': 85,
    'Fascinating': 85,
    'Fast': 75,
    'Fearless': 80,
    'Feisty': 80,
    'Feminine': 75,
    'Fertile': 75,
    'Fervent': 80,
    'Fierce': 75,
    'Fine': 75,
    'Firm': 75,
    'Fit': 75,
    'Flamboyant': 80,
    'Flawless': 85,
    'Flexible': 75,
    'Flowing': 75,
    'Fluent': 80,
    'Focused': 80,
    'Fond': 75,
    'Forceful': 75,
    'Forgiving': 85,
    'Formal': 75,
    'Forthright': 75,
    'Fortunate': 85,
    'Fragrant': 75,
    'Frank': 75,
    'Free': 75,
    'Free-spirited': 75,
    'Fresh': 75,
    'Friendly': 85,
    'Fruitful': 75,
    'Fulfilled': 85,
    'Fulfilling': 85,
    'Full': 75,
    'Fun': 80,
    'Funny': 80,
    'Futuristic': 75,
    'Gallant': 80,
    'Generous': 85,
    'Gentle': 80,
    'Genuine': 85,
    'Gifted': 80,
    'Giving': 85,
    'Glad': 80,
    'Glamorous': 80,
    'Gleaming': 75,
    'Glistening': 75,
    'Glorious': 85,
    'Glowing': 80,
    'Godly': 75,
    'Golden': 75,
    'Good': 75,
    'Good-natured': 80,
    'Gorgeous': 85,
    'Graceful': 85,
    'Gracious': 85,
    'Grand': 80,
    'Grateful': 85,
    'Great': 80,
    'Green': 75,
    'Gregarious': 80,
    'Groundbreaking': 75,
    'Growing': 75,
    'Grown-up': 75,
    'Guided': 75,
    'Guiding': 75,
    'Hale': 75,
    'Handsome': 85,
    'Handy': 75,
    'Hard-working': 80,
    'Harmonious': 80,
    'Healing': 85,
    'Healthy': 75,
    'Heartfelt': 85,
    'Hearty': 80,
    'Heavenly': 80,
    'Helpful': 85,
    'Heroic': 80,
    'High-quality': 80,
    'Hilarious': 80,
    'Honest': 75,
    'Honorable': 75,
    'Hopeful': 85,
    'Hospitable': 80,
    'Hot': 75,
    'Humble': 80,
    'Humorous': 80,
    'Ideal': 85,
    'Idealistic': 80,
    'Illustrious': 80,
    'Imaginative': 85,
    'Immense': 75,
    'Impartial': 75,
    'Impeccable': 85,
    'Important': 75,
    'Impressive': 85,
    'Incredible': 90,
    'Independent': 75,
    'Individualistic': 75,
    'Industrious': 80,
    'Influential': 80,
    'Informative': 75,
    'Innovative': 85,
    'Inquisitive': 75,
    'Insightful': 80,
    'Inspired': 85,
    'Inspiring': 85,
    'Inspirited': 80,
    'Intelligent': 80,
    'Intense': 75,
    'Interactive': 75,
    'Interested': 75,
    'Interesting': 85,
    'Intimate': 80,
    'Intriguing': 80,
    'Intuitive': 75,
    'Inventive': 80,
    'Invigorating': 85,
    'Invincible': 80,
    'Irreplaceable': 80,
    'Irresistible': 85,
    'Jocular': 80,
    'Joint': 75,
    'Jolly': 80,
    'Jovial': 80,
    'Joyful': 85,
    'Joyous': 85,
    'Juicy': 75,
    'Just': 75,
    'Keen': 75,
    'Kind': 85,
    'Kind-hearted': 85,
    'Knowing': 75,
    'Knowledgeable': 80,
    'Laid-back': 75,
    'Large': 75,
    'Lasting': 75,
    'Laughable': 75,
    'Laughter': 85,
    'Leading': 75,
    'Lean': 75,
    'Learning': 75,
    'Legendary': 80,
    'Leisurely': 75,
    'Lenient': 80,
    'Liberated': 75,
    'Liberal': 75,
    'Lighthearted': 85,
    'Lighting': 75,
    'Likable': 80,
    'Like-minded': 75,
    'Lively': 80,
    'Logical': 75,
    'Long-lasting': 75,
    'Lovable': 85,
    'Loving': 85,
    'Loyal': 85,
    'Lucid': 75,
    'Lucky': 85,
    'Luminous': 75,
    'Luscious': 75,
    'Luxurious': 80,
    'Magnanimous': 85,
    'Magnetic': 80,
    'Magnificent': 90,
    'Majestic': 85,
    'Major': 75,
    'Marvelous': 90,
    'Masterful': 80,
    'Matchless': 80,
    'Mature': 75,
    'Meaningful': 85,
    'Measured': 75,
    'Meditative': 85,
    'Mellifluous': 75,
    'Memorable': 85,
    'Mendacious': -80,
    'Menial': -75,
    'Merciful': 85,
    'Mercurial': -75,
    'Merry': 80,
    'Methodical': 75,
    'Meticulous': 80,
    'Mighty': 80,
    'Mind-blowing': 90,
    'Mindful': 85,
    'Miraculous': 90,
    'Mirthful': 80,
    'Miserable': -85,
    'Miserly': -80,
    'Misguided': -80,
    'Mistaken': -75,
    'Misunderstood': -75,
    'Mischievous': -80,
    'Modern': 75,
    'Modest': 75,
    'Momentous': 80,
    'Monumental': 85,
    'Moral': 75,
    'Motivated': 80,
    'Motivating': 80,
    'Mouth-watering': 75,
    'Moving': 85,
    'Multifaceted': 75,
    'Mundane': -75,
    'Muscular': 75,
    'Mysterious': 75,
    'Mystical': 80,
    'Naked': -75,
    'Narcissistic': -80,
    'Narrow-minded': -80,
    'Nasty': -85,
    'Natural': 75,
    'Naughty': -80,
    'Nauseating': -85,
    'Nauseous': -85,
    'Nautical': 75,
    'Neat': 80,
    'Necessary': 75,
    'Negative': -75,
    'Neglected': -85,
    'Negligent': -80,
    'Nervous': -75,
    'Neurotic': -80,
    'Neutral': 75,
    'New': 75,
    'Nice': 80,
    'Nimble': 75,
    'Noble': 85,
    'Noisy': -75,
    'Nonchalant': -75,
    'Noncommittal': -75,
    'Nonconformist': 75,
    'Nondescript': -75,
    'Nonetheless': 75,
    'Nonpareil': 80,
    'Nonsensical': -80,
    'Nostalgic': 80,
    'Notable': 75,
    'Noteworthy': 80,
    'Nourishing': 85,
    'Novel': 80,
    'Nurturing': 85,
    'Nutritious': 80,
    'Obedient': 80,
    'Objective': 75,
    'Obliging': 85,
    'Obscure': -75,
    'Observant': 80,
    'Obstinate': -80,
    'Obstructive': -80,
    'Obtuse': -80,
    'Like': 20,
    'Arrest': -50,
    # 'Parents': -100,
    # 'The': 20
    }

    #Asked ChatGPT to give a list of words

    return word_rankings

def custom_sentiment_analysis():
    """
    This function is very similar to headlines_sentiment(), but I conduct
    the sentiment analysis myself rather then relying on the nltk package.
    The function uses the custom_words_ranking() dictionary created by ChatGPT
    in order to develop the market sentiment. Clearly, there are less words 
    in my dictionary than the nltk library, so it won't be as accurate.
    """

    total_sentiment = 0

    for i in range(len(news_article_headlines())):
        sentence = news_article_headlines()[i]
        #print(sentence)
        
        split_sentence = sentence.split()
        for i in range(len(split_sentence)):
            #print(split_sentence[i])
            split_sentence[i].strip()
            #print(split_sentence[i])
            # if news_article_headlines().has_key(split_sentence[i]):
            if split_sentence[i] in custom_word_rankings():
                #print(custom_word_rankings()[split_sentence[i]])
                total_sentiment += custom_word_rankings()[split_sentence[i]]

    average_sentiment = total_sentiment/(len(news_article_headlines()))
    return average_sentiment

    

def main():
    print(news_article_headlines()) #prints a list of top news articles
    print(headlines_sentiment()) #conducts a market sentiment analysis with nltk on top news articles
    print(sentiment_result(headlines_sentiment)) #summarizes the number
    print(custom_sentiment_analysis()) #a dictionary of words and their ranking from -100 to 100
    print(sentiment_result(custom_sentiment_analysis)) #conducts a market sentiment analysis with custom words
    
if __name__ == "__main__":
    main()